DROP TABLE IF EXISTS Crash_Data;

CREATE TABLE Crash_Data (
    OBJECTID integer primary key,
    ACCIDENT_NO varchar,
    ABS_CODE varchar,
    ACCIDENT_STATUS varchar,
    ACCIDENT_DATE varchar,
    ACCIDENT_TIME varchar,
    ALCOHOLTIME varchar,
    ACCIDENT_TYPE varchar,
    DAY_OF_WEEK varchar,
    DCA_CODE varchar, 
    HIT_RUN_FLAG varchar, 
    LIGHT_CONDITION varchar, 
    POLICE_ATTEND varchar, 
    ROAD_GEOMETRY varchar, 
    SEVERITY varchar, 
    SPEED_ZONE varchar, 
    RUN_OFFROAD varchar, 
    NODE_ID varchar, 
    LONGITUDE varchar, 
    LATITUDE varchar, 
    NODE_TYPE varchar, 
    LGA_NAME varchar, 
    REGION_NAME varchar, 
    VICGRID_X varchar, 
    VICGRID_Y varchar, 
    TOTAL_PERSONS varchar, 
    INJ_OR_FATAL varchar, 
    FATALITY varchar, 
    SERIOUSINJURY varchar, 
    OTHERINJURY varchar, 
    NONINJURED varchar, 
    MALES varchar, 
    FEMALES varchar, 
    BICYCLIST varchar, 
    PASSENGER varchar, 
    DRIVER varchar, 
    PEDESTRIAN varchar, 
    PILLION varchar, 
    MOTORIST varchar, 
    UNKNOWN varchar, 
    PED_CYCLIST_5_12 varchar, 
    PED_CYCLIST_13_18 varchar, 
    OLD_PEDESTRIAN varchar, 
    OLD_DRIVER varchar, 
    YOUNG_DRIVER varchar, 
    ALCOHOL_RELATED varchar, 
    UNLICENCSED varchar, 
    NO_OF_VEHICLES varchar, 
    HEAVYVEHICLE varchar, 
    PASSENGERVEHICLE varchar, 
    MOTORCYCLE varchar, 
    PUBLICVEHICLE varchar, 
    DEG_URBAN_NAME varchar, 
    DEG_URBAN_ALL varchar, 
    LGA_NAME_ALL varchar, 
    REGION_NAME_ALL varchar, 
    SRNS varchar, 
    SRNS_ALL varchar, 
    RMA varchar, 
    RMA_ALL varchar, 
    DIVIDED varchar, 
    DIVIDED_ALL varchar, 
    STAT_DIV_NAME varchar
);

